[package]
name = "api"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
common.workspace = true
deadpool-redis.workspace = true
futures-util.workspace = true
ipnet.workspace = true
ingestion.workspace = true
processor.workspace = true
qdrant-client.workspace = true
redis.workspace = true
reqwest.workspace = true
retrieval.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
subtle.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
async-trait.workspace = true
tower = { version = "0.5", features = ["util"] }
